### ISSUE TITLE
Move kits to a base params definition (similar to igenomes)

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/NGI-ExoSeq#16]
I'll move the description of all kits and genome files to a base params definition and document this. 

e.g. you only specify `-genome "blagarbl"` and the pipeline looks in the cluster specific configuration / base configuration where the genome files for the requested files are located at. 

- [ ] move paths to a certain "base dir" (and not hard link them)
- [ ] documentation update to specify what is expected in such a path
- [ ] test things

**Comment by ewels** [comment]
Depending on filesize, it could also be nice to supply a few common sets for simple download / integration. Need to think on what and where though.

**Comment by apeltzer** [comment]
I think we could e.g. download / offer a download function for the GATK b37 dataset. That should be feasible, because the required reference databases (dbSNP, Illumina Omni, Mills Gold for Indels, ...) are all there on an FTP and just waiting for us ;-) 

For other datasets, e.g. the updated GRCh38 there are similar resources that we could offer to automatically download for users.

**Comment by apeltzer** [comment]
Migrated to https://github.com/nf-core/ExoSeq/issues/7
