### ISSUE TITLE
Indel realignment obsolete

### ISSUE THREAD

**Issue by marchoeppner** [SciLifeLab/NGI-ExoSeq#20]
Hi!

Took some inspiration from your project for another exome pipeline I am working on. I noticed that you are still using the indel realignment step as by the older GATK best practice. I just wanted to point out that this step is no longer considered best practice when HaplotypeCaller is used:
https://software.broadinstitute.org/gatk/blog?id=7847

Will cut down on the processing time significantly, I reckon. 

Cheers,
Marc

**Comment by ewels** [comment]
Thanks Marc! I believe that this is one of the many things changed in the huge pull request by @apeltzer  in #9 

We're planning to get that merged into master very soon. It might be worth taking a look at his fork if you're curious in the mean time, as that's now 200 commits ahead of this repo until the PR is merged: https://github.com/apeltzer/NGI-ExoSeq/

**Comment by apeltzer** [comment]
Already implemented in https://github.com/nf-core/ExoSeq , closing this
