### ISSUE TITLE
To be implemented

### ISSUE THREAD

**Issue by senthil10** [SciLifeLab/NGI-ExoSeq#3]
The followings have to be implemented yet

- [ ] Documentation
- [ ] Travis test
- [ ] Reports (`MultiQC`)
- [ ] Possible standalone images (`Docker/Singularity`)
- [ ] Final code review (configs, logging, mailing)

**Comment by apeltzer** [comment]
I will send you a pull request from (https://github.com/apeltzer/NGI-ExoSeq) that should at least cover:

- [ ] Reports
- [ ] Singularity images
- [ ] Some documentation

I tried to follow the GATK devs documentation more strictly but am open to discussing things here too. Also, we'd have some more detailed feature requests that I will contribute here as issues and then submit here, too. 

My future Git Messages will also feature more stringent comments, I, unfortunately, didn't follow any guidelines there and often have some "small fixing..." comments in there, too.

**Comment by apeltzer** [comment]
I also added some more modules (QualiMap for BAM stats instead of twice Picard with apparently deprecated metrics tools that are left out with GATK v4 soon)

**Comment by apeltzer** [comment]
I opened #13 , #12 , #11 , #10  to make things easier to track when multiple people are working on them.  This ticket could be closed then in the future ;-)

**Comment by apeltzer** [comment]
This could be closed, I cant do it :-(
