### ISSUE TITLE
Try to generalise pipeline more

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-ExoSeq#5]
At the moment some of the commands are fairly tied to the NGI infrastructure (eg. regexes that assume sample names looking like `P1234`). It would be good to try to generalise this as much as possible, moving stuff out into `param` variables if required.

**Comment by apeltzer** [comment]
My pull request will mostly add support for things here. I'll also try to integrate things from NGI-RNAseq and our recently discussed pipeline structure (e.g. documentation here). Started to restructure in my repo already before we had NGI-NFcookiecutter available ;-)
